import type { Metadata } from "next";
import "./globals.css";
//import { getSession } from "next-auth/react";
//import Providers from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  //const session = await getSession()
  
  return (
    <html lang="en">
      <body>
        {/* <Providers session={session}> */}
          {children}
        {/* </Providers> * */}
      </body>
    </html>
  );
}
